name: terraform-automation

on:
  push:
  pull_request:

jobs:
  terraform_plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./examples

    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/workflows/script.sh"
          "${GITHUB_WORKSPACE}/.github/workflows/script.sh"

          terraform plan

  terraform_apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    needs: terraform_plan

    defaults:
      run:
        shell: bash
        working-directory: ./examples

    steps: 
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup GCP Service Account
      uses: google-github-actions/setup-gcloud@master
      with:
        version: 'latest'
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
        
    # Provision resources via Terraform        
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        chmod +x "${GITHUB_WORKSPACE}/.github/workflows/script.sh"
        "${GITHUB_WORKSPACE}/.github/workflows/script.sh"
        terraform apply --auto-approve

