name: terraform

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  terraform:
    name: 'Terraform Automation'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./examples

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup GCP Service Account
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        run: terraform fmt -recursive

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan -out "tf_plan"

      # Upload tf_plan for 1 hr
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: tf_plan
          path: tf_plan
          retention-days: 1
